# Generated by Django 4.1 on 2023-03-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ownerprofile_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_started',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
