# Generated by Django 4.1 on 2023-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_site_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
