# Generated by Django 4.1 on 2023-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_project_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manpower',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
