# Generated by Django 4.1 on 2023-03-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_systemsummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemsummary',
            unique_together=set(),
        ),
    ]
