# Generated by Django 4.1 on 2023-03-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSummary',
        ),
    ]
