# Generated by Django 4.1 on 2023-03-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='office_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='core.project'),
        ),
    ]
