# Generated by Django 4.1 on 2023-03-16 04:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_address_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='way',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
